#!/bin/bash

#############################################################################
#author       :    fushikai
#date         :    20190430
#linux_version:    Red Hat Enterprise Linux Server release 6.7
#dsc          :
#       Used to install, pause,or uninstall software
#
#    
#revision history:
#       
#
#############################################################################

#软件版本
versionNo="software version number: v0.0.0.1"


#load system environment configuration
if [ -f /etc/profile ]; then
    . /etc/profile >/dev/null 2>&1
fi
if [ -f ~/.bash_profile ];then
    . ~/.bash_profile >/dev/null 2>&1
fi

baseDir=$(dirname $0)

fncFName=diyFuncBysky.func

fncFile="${baseDir}/shfunc/${fncFName}"


if [ ! -x "${fncFile}" ];then
    chmod u+x "${fncFile}"
    echo -e "\nchmod u+x ${fncFile}\n"
fi

#Load shell function file
. ${fncFile}


logFNDate="$(date '+%Y%m%d')"

pwdDir="$(pwd)"
uName=$(whoami)
tEdFile="/var/spool/cron/${uName}"
#tEdFile="./tktk"

thostname=$(hostname)
#fixhname="fuskTest"
#fixhname="ScadaServer"
#fixhname="fuskTest"

if [[ ! -z "${fixhname}" && "${thostname}" != "${fixhname}" ]];then
    echo -e "\n\tError: Please execute on the scada server!!\n"
    exit 1
fi

if [ "${uName}" != "root" ];then
    echo -e "\n\tError: Please execute as root!!\n"
    exit 2
fi


#echo "--pwdDir=[$pwdDir}]--uName=[${uName}]---tEdFile=[${tEdFile}]"

exShellPre="killProgramBycfg"
srcShellFile="${baseDir}/killprogram/${exShellPre}.sh"
srcCfgFile="${baseDir}/killprogram/killByxxcfg.cfg"

exShellFile="/zfmd/wpfs20/startup/${exShellPre}.sh"
exCfgFile="/zfmd/wpfs20/startup/killByxxcfg.cfg"

logDir="/zfmd/wpfs20/startup/log"

toDirP=/zfmd/wpfs20
tobakdir="${toDirP}/backup/${exShellPre}"

mkpDir ${tobakdir}
mkpDir ${logDir}

if [ ! -e ${srcShellFile} ];then
    echo -e "\n\tERROR: File [ ${exShellFile} ] does not exist!!\n"
    exit 1
fi

function upOrInstallSh()
{
    updateFile "${srcShellFile}" "${exShellFile}" "${tobakdir}"
    if [ ! -x "${exShellFile}" ];then
        chmod u+x "${exShellFile}"
        echo "chmod u+x ${exShellFile}"
    fi
    if [ ! -e "${exCfgFile}" ];then
        updateFile "${srcCfgFile}" "${exCfgFile}" "${tobakdir}"
    fi
    return 0
}



cronCycle=1

if [[ ${cronCycle} -gt 1 && ${cronCycle} -lt 60 ]];then
    tS0Add="*/${cronCycle} * * * * ${exShellFile} >>${logDir}/cron${exShellPre}.log 2>&1"
else
    tS0Add="* * * * * ${exShellFile} >>${logDir}/cron${exShellPre}.log 2>&1"
fi

#echo "---tS0Add=[${tS0Add}]---"

if [[ ! -z "${tEdFile}" && -e  ${tEdFile} ]];then
    tS0Num=$(sed -n "/^[^#].*${exShellPre}.sh/p" ${tEdFile}|wc -l)
    tS0NumCom=$(sed -n "/^#\+.*${exShellPre}.sh/p" ${tEdFile}|wc -l)
fi

#echo "----tS0Num=[${tS0Num}],tS0NumCom=[${tS0NumCom}]----"

function addComToCron()
{
    if [ -z "${tS0Num}" ];then
        return 0
    fi
    if [ ${tS0Num} -lt 1 ];then
        return 0
    fi
    sed -n "/^[^#].*${exShellPre}.sh/=" ${tEdFile}|while read tnaa
    do
        sed -i "${tnaa}s/^/#/g" ${tEdFile}
    done
    return 0
}

function delComToCron()
{
    if [ -z "${tS0NumCom}" ];then
        return 0
    fi
    if [ ${tS0NumCom} -lt 1 ];then
        return 0
    fi
    sed -n "/^#\+.*${exShellPre}.sh/=" ${tEdFile}|while read tnaa
    do
        sed -i "${tnaa}s/^#\+//g" ${tEdFile}
    done
    return 0
}


function delItemToCron()
{
    if [[ ! -z "${tS0NumCom}" &&  ${tS0NumCom} -gt 0 ]];then
        sed -n "/^#\+.*${exShellPre}.sh/=" ${tEdFile}|while read tnaa
        do
            #echo "---$tnaa----"
            sed -i "${tnaa} d" ${tEdFile}
        done
    fi
    if [[ ! -z "${tS0Num}" &&  ${tS0Num} -gt 0 ]];then
        sed -n "/^[^#].*${exShellPre}.sh/=" ${tEdFile}|while read tnaa
        do
            #echo "---$tnaa----"
            sed -i "${tnaa} d" ${tEdFile}
        done
    fi
    return 0
}

function addItemToCron()
{
    delItemToCron
    if [[ ! -z "${tEdFile}" && ! -e  ${tEdFile} ]];then
            #echo "---+++++++----"
        echo "${tS0Add}">> ${tEdFile}
        return 0
    fi
    if [[ ! -z "${tEdFile}" &&  -e  ${tEdFile} ]];then
            #echo "---$tnaa----"
        if [ ! -s "${tEdFile}" ];then
            #echo "null add"
            echo "${tS0Add}">> ${tEdFile}
        else
            sed -i "$ a${tS0Add}" ${tEdFile}
        fi
    fi
    return 0
}


prompct1="       
       请输入如下数字，选择相应的操作：
                [1].安装或升级脚本
                [2].卸载脚本
                [3].暂停脚本
                [4].重新使脚本可用
                [5].退出，什么都不做
      你的选择是: "


#echo "---${prompct1}---"


while ((1))
do

    read -n 1 -p "${prompct1}" opType

    if [[ ${opType} -ne 1 && ${opType} -ne 2 && ${opType} -ne 3 && ${opType} -ne 4 && ${opType} -ne 5 ]];then
    echo ""
    echo " -----------ERROR---------------------:Input errors,please re-enter!"
        continue
    fi

    break

done
[ ${opType} -eq 5 ] && echo "" && exit 0

if [ ${opType} -eq 1 ];then
    upOrInstallSh
    addItemToCron
elif [ ${opType} -eq 2 ];then
    delItemToCron
elif [ ${opType} -eq 3 ];then
    addComToCron
elif [ ${opType} -eq 4 ];then
    delComToCron
else
    echo -e "\n\t ERROR:logic error!!!!\n"
fi


    echo ""
    echo -e "\n\tThe configuration after operation is as follows:"
    echo ""
    cat ${tEdFile} 
    echo -e "\n"    



echo -e "\n\t$(date +%Y/%m/%d-%H:%M:%S.%N):script [ $0 ] runs complete!!\n\n"

exit 0
