#!/bin/bash

#############################################################################
#author: fusk
#date:   20180809
#dsc:    This script monitor the pid of some programs,prints and exits 
#        if all monitor pids appear,otherwise waits 300 seconds before 
#        exiting  
#
#############################################################################

if [[ $# -lt 1 ]];then
    echo ""
    echo "input error,please input like this:"
    echo "                        waitpidof <program_name>[<program_name2>...<program_namen>]"
    echo ""
    exit 1
fi

inputNum=$#

i=1
for pName in $@;do
	#echo ${pName}
	inPNmae[$i]=${pName}
    doFlag[$i]=0
	((i=i+1))
done

echo "..."
echo "Monitor the < $@ >'s PID ..."


i=0
tmOutSec=300

while :
do
	for t in $(seq ${inputNum});do
			if [[ ${doFlag[$t]} -eq 0 &&  $(pidof -x ${inPNmae[$t]}|wc -l) -gt 0 ]];then
				echo "${inPNmae[$t]} PID=[$(pidof -x ${inPNmae[$t]})]"
				echo ""
				doFlag[$t]=1
			fi
	done

	brkFlag=0
	for t in $(seq ${inputNum});do
		if [[ ${doFlag[$t]} -eq 0 ]];then
			brkFlag=1
			break
		fi
	done

	if [[ ${brkFlag} -eq 0 ]];then
		break
	fi

    sleep 1
    ((i=i+1))

    if [[ $i -gt ${tmOutSec} ]];then
        echo "Exceeding the timeout period of ${tmOutSec} seconds,the program monitor exits"
        echo ""
        break
    fi
done


exit 0


