#!/bin/bash
#
#############################################################################
#author       :    fushikai
#date         :    20190519
#linux_version:    Red Hat Enterprise Linux Server release 6.7
#dsc          :
#       Manage software firewalls in the system
#
#    
#revision history:
#   v0.0.0.1 @ 20190519
#   2019-09-23 modify v0.0.0.1 version to V20.01.000
#       
#
#############################################################################

baseDirM=$(dirname $0)
funcBaseDir="${baseDirM}/basesh"
funcFile="${funcBaseDir}/functions"
toAddShFile="${funcBaseDir}/addfw"

tUID=$(id -u)
if [[ -z "${tUID}" || ${tUID} -ne 0 ]];then

    echo -e "\n\tError:\e[1;31m Please execute as root!\e[0m the current user is ${USER}\n"
    exit 1
fi



if [ ! -e ${funcFile} ];then
    echo -e "\n\tError: File [${funcFile}] does not exist!!\n"
    exit 1
fi

. ${funcFile}



prompct1="
    请输入下面选项前的数字，选择相应的操作:

        [0].按照配置文件的内容，设置系统防火墙

        [1].在本机永久打开防火墙

        [2].在本机永久停用防火墙

        [3].清空现有防火墙的规则

        [4].查看系统中防火墙的配置

        [5].退出

    你的选择是: "
#echo "${prompct1}"
prompct2="
    请确认配置文件已经先配置完成:

        [Y/y].确认已经配置完成

        [N/n].还未配置完成

    请确认: "

while ((1))
do

    read -n 1 -p "${prompct1}" opType

    tcheck=$(echo "${opType}"|sed -n '/^[0-9]$/p'|wc -l)

    if [[ ${tcheck} -eq 0 || ${opType} -ne 0 && ${opType} -ne 1 && ${opType} -ne 2 && ${opType} -ne 3 && ${opType} -ne 4 && ${opType} -ne 5 ]];then
        echo ""
        echo -e "\n -----------\e[1;31mERROR\e[0m---------------------:\e[1;31m输入错误，请按提示要求重新输入!\e[0m"
        continue
    fi

    break

done
[ ${opType} -eq 5 ] && echo "" && exit 0

if [ ${opType} -eq 0 ];then

    while ((1))
    do

        echo -e "\n"
        read -n 1 -p "${prompct2}" opYes

        if [[ ${opYes} != "Y" && ${opYes} != "y" && ${opYes} != "N" && ${opYes} != "n" ]];then
        echo ""
        echo -e "\n -----------\e[1;31mERROR\e[0m---------------------:\e[1;31m输入错误，请按提示要求重新输入!\e[0m"
            continue
        fi

        break

    done


fi

echo -e "\n"

if [[ ${opYes} == "N" || ${opYes} == "n" ]];then
    exit 0
fi 


case ${opType} in
    0)
        if [ ! -e "${toAddShFile}" ];then
            echo -e "\n\t\e[1;31mError:The script [${toAddShFile}] to be executed does not exist \e[0m\n"
            exit 6
        fi
        [ ! -x "${toAddShFile}" ] && chmod u+x ${toAddShFile}
        ${toAddShFile}
        ;;
    1)
        echo -e "\n\t\e[1;31mdebugFlag=[${debugFlag}]\e[0m\n"
        FW_START
        ;;
    2)
        echo -e "\n\t\e[1;31mdebugFlag=[${debugFlag}]\e[0m\n"
        FW_STOP
        ;;
    3)
        echo -e "\n\t\e[1;31mdebugFlag=[${debugFlag}]\e[0m\n"
        FW_CLEAR
        ;;
    4)
        echo -e "\n\t\e[1;31mdebugFlag=[${debugFlag}]\e[0m\n"
        FW_VIEW
        ;;
    *)
        echo -e "\n\t\e[1;31mERROR:系统逻辑错误!\e[0m\n"
        exit 5
        ;;
esac

echo -e "\n"

exit 0
